---
title: "R Notebook"
output: html_notebook
---

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```

引入套件
```{r}
library(stringr)
```


```{r}
install.packages("stringr")
```

```{r}
str
```


```{r}
a <- 2
3 -> b
```


```{r}
`a`
```


```{r}
a<-5
a2<-5L
```
```{r}
aVector<-c(5,6,7)
a2Vector<-c(5L,6L,7L)
```

```{r}
class(a)
class(a2)
class(aVector)
```

```{r}
class(a2Vector)
```

```{r}
b<-"你好"
```

```{r}
bVector<-c("你好","How are you?")
```


```{r}
class(b)
```


```{r}
bVector<-c("你好","How are you?")
```

```{r}
class(bVector)
```
```{r}
class(b
      )
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

PlasticContainer

plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer

plasticContainer[["greenBox"]] 
plasticContainer[[1]]

```

```{r}
plasticContainer[["greenBox"]][[1]]

```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
成績單[["個經"]]

成績單[[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord

studentRecord[[2]]

studentRecord[[4]][[3]]
```

```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
plasticContainer
extract1 <- plasticContainer[c("greenBox")]
extract1
extract2 <- plasticContainer[[c("greenBox")]]
extract2
```

```{r}
extract1[[1]][1]
extract2[1]
```
```{r}
extract1[[1]][1]
extract2[[1]]
```

```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

```

```{r}
plasticContainer
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```

```{r}
your_github_username <- "christina4473"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```



```{r}
commitCheck[[4]][["commit"]][["committer"]][["date"]]
```
```{r}
commitCheck[[4]]$"commit"[["committer"]][["date"]]
```

```{r}
commitCheck[[4]][["commit"]][["committer"]][["date"]] -> commitDate
with_tz(commitDate,tzone="Asia/Taipei")
```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
filmVotingData$Timestamp
filmVotingData[["Timestamp"]]
filmVotingData$`Timestamp`
```
```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
```
```{r}
sum(logiCorrect)
```

```{r}
favoriteTwo[logiCorrect] -> validFavoriteTwo
validFavoriteTwo
```

```{r}
stulist <- t
```

